// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopSphere.API.Data;

#nullable disable

namespace ShopSphere.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250407133222_AddCartTable2")]
    partial class AddCartTable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopSphere.API.Entitiy.CartItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CartModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartModelId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopSphere.API.Entitiy.CartModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ShopSphere.API.Entitiy.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63e2f02c-c529-4ee5-9eff-7dfe31288098"),
                            Description = "Iphone 16 Description",
                            ImageUrl = "1.png",
                            Name = "Iphone 16",
                            Price = 70000m,
                            Stock = 10,
                            isActive = true
                        },
                        new
                        {
                            Id = new Guid("a7053963-5521-4672-bc8d-73faff51686f"),
                            Description = "Iphone 15 Description",
                            ImageUrl = "2.jpg",
                            Name = "Iphone 15",
                            Price = 60000m,
                            Stock = 20,
                            isActive = true
                        },
                        new
                        {
                            Id = new Guid("1557224f-acc0-4bf4-a496-0ba39fe2cf44"),
                            Description = "Iphone 14 Description",
                            ImageUrl = "3.png",
                            Name = "Iphone 14",
                            Price = 50000m,
                            Stock = 30,
                            isActive = true
                        });
                });

            modelBuilder.Entity("ShopSphere.API.Entitiy.CartItemModel", b =>
                {
                    b.HasOne("ShopSphere.API.Entitiy.CartModel", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartModelId");

                    b.HasOne("ShopSphere.API.Entitiy.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopSphere.API.Entitiy.CartModel", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
